name: test6
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  csv: ^4.0.3
  http: ^0.12.0+2
  enum_to_string: ^1.0.7
  eva_icons_flutter: ^1.0.4
  flutter_icons: ^0.3.0
  provider: ^2.0.0+1
  photo_view: ^0.5.0
  flutter_typeahead: ^1.6.1
  flutter_image: ^2.0.0
  url_launcher: ^5.1.4
  recase: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
